arch:
  - aarch64
  - amd64
description: An open source command line RatioMaster with WebUI
hassio_api: true
image: ghcr.io/lklynet/aurral
ingress: true
ingress_entry: entry
map:
  - addon_config:rw
  - homeassistant_config:rw
name: Aurral2
ports:
  3001/tcp: null
  3001/tcp: 3001
ports_description:
  3001/tcp: torrent port (not required)
  3001/tcp: Web UI port (required)
slug: aurral2
udev: true
url: https://github.com/alexbelgium/hassio-addons
version: 2.1.37-4
