name: Lidarr
version: pr-plugins
slug: lidarr
description: Looks and smells like Sonarr but made for music
url: https://github.com/olliedown/homeassistant/lidarr/README.md
codenotary: codenotary@frenck.dev
webui: http://[HOST]:[PORT:8686]
init: false
arch:
- aarch64
- amd64
- armv7
map:
- addon_config:rw
- share:rw
- media:rw
ports:
  8686/tcp: 8686
image: ghcr.io/hotio/lidarr
privileged:
  - SYS_ADMIN
  - NET_ADMIN
  - NET_RAW
  - DAC_READ_SEARCH
environment:
  PGID: 0
  PGUD: 0
